todoproject/todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<int:taskid>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/', views.TodoListView.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.TodoDetailView.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.TodoUpdateView.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TodoDeleteView.as_view(), name='cbvdelete'),
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path('admin/', admin.site.urls),


    path('', include('todoapp.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from .models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView

from .forms import TodoForm
from .models import Task

# Create your views here.

class TodoListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'

class TodoDetailView(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'

class TodoUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail', kwargs={'pk': self.object.id})

class TodoDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')

def home(requset):
    task1 = Task.objects.all()
    if requset.method == 'POST':
        name = requset.POST.get('task', '')
        priority = requset.POST.get('priority', '')
        date = requset.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(requset, 'home.html', {'task1': task1})

def detail(request):
    task1 = Task.objects.all()
    return render(request,'detail.html',{'task':task})

def delete(request, taskid):
    task = Task.objects.get(id=taskid)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')

def update(request, id):
    task = Task.objects.get(id=id)
    form = TodoForm(request.POST or None, instance=task)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'task': task, 'form': form})

todoproject/todoapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDo Base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/todoapp/templates/delete.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <p>Are you sure delete this task??</p>
    <button type="submit" class="btn btn-success">Confirm</button>
</form>

{% endblock %}

todoproject/todoapp/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="shadow card">
        <div class="card-body">
            <h5 class="card-title">{{ task.name }}</h5>
            <p><b>{{ task.priority }}</b></p>
            <p><b>{{ task.date }}</b></p>
            <a class="btn btn-danger" href="{% url 'delete' task.id %}">Done</a>
            <a class="btn btn-info" href="{% url 'update' task.id %}">Update</a>
        </div>
    </div>
{% endblock %}

todoproject/todoapp/templates/edit.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Confirm</button>
    </form>
{% endblock %}

todoproject/todoapp/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="banner">
                    <div align="center">
                        <h1  style="background-color:#00FFFF">ToDo</h1>
                    </div>
                    <div class="banner-text"  >

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container" >
        <div class="row">
            <div class="col-md-6">
                <form method="POST" class="p-3 shadow">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="task" placeholder="Task Name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="priority" placeholder="Enter Priority">
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="date" class="form-control" name="date" placeholder="Enter date">
                    </div><br>
                    <input type="submit" class="btn btn-primary">
                </form>
            </div>
            <div class="col-md-6">
                <h4>Task To Be Completed</h4>
                {% for i in task1 %}
                    <div class="shadow card">
                        <div class="card-body">
                            <h5 class="card-title">{{i.name}}</h5>
                            <p><b>{{i.priority}}</b></p>
                            <p><b>{{i.date}}</b></p>
                            <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                            <a class="btn btn-info" href="{% url 'todoapp:update' i.id %}">Update</a>
                        </div>
                    </div>
                    <br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

todoproject/todoapp/templates/update.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                Task Update
            </div>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Confirm</button>
            </form>
        </div>
    </div>
{% endblock %}